name: Build, test and (if release) deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Test: Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

#      - name: "Format: ruff"
#        run: ruff format . --diff

      - name: "Lint: ruff"
        run: ruff check .

      - name: "Test: pytest"
        run: pytest

  release-please:
    name: release-please
    if: github.ref_name == 'main'
    needs: test
    permissions:
      issues: write
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yaml

  build:
    name: Build
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Build Package
        run: |
          pip install build
          export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_FMU_PEM=$GITHUB_REF_NAME
          python -m build

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmu-pem-dist
          path: dist/

  update-documentation:
    name: Update Documentation
    if: github.ref_name == 'main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 # required for create-json-schema
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: documentation/package-lock.json

      - name: Install Node Dependencies
        working-directory: ./documentation
        run: npm ci

      - name: Create JSON Schema
        working-directory: ./documentation
        run: npm run create-json-schema

      - name: Build Documentation
        working-directory: ./documentation
        run: npm run docs:build

      - name: Deploy Documentation to GitHub Pages
        run: echo "Don't actually do this in my fork"

  deploy:
    name: Publish Package to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fmu-pem
    permissions:
      id-token: write # required for Trusted Publishing to PyPI

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: fmu-pem-dist
          path: dist/

      - name: Publish Package to PyPI
        run: echo "Don't actually do this in my fork"
