name: Build, test and (if release) deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Test: Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

#      - name: "Format: ruff"
#        run: ruff format . --diff

      - name: "Lint: ruff"
        run: ruff check .

      - name: "Test: pytest"
        run: pytest

  release-please:
    name: release-please
    if: github.ref_name == 'main'
    needs: test
    permissions:
      issues: write
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yaml

  build:
    name: Build
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Build Package
        run: |
          pip install build
          export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_FMU_PEM=$GITHUB_REF_NAME
          python -m build

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmu-pem-dist
          path: dist/

  update-documentation:
    name: Update Documentation
    if: github.ref_name == 'main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 # required for create-json-schema
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Build Documentation
        working-directory: ./documentation
        run: |
          npm ci
          npm run create-json-schema
          npm run docs:build

      - name: Deploy Documentation to GitHub Pages
        run: |
          # Move the built documentation out of working directory, in order to delete everything else afterwards
          cp -R ./documentation/docs/.vitepress/dist ../dist

          git config --local user.email "fmu-pem-github-action"
          git config --local user.name "fmu-pem-github-action"
          git fetch origin gh-pages
          git checkout -f --track origin/gh-pages
          git clean -f -f -d -x
          git rm -r *

          cp -R ../dist/* .

          git add .

          if git diff-index --quiet HEAD; then
            echo "No changes in documentation. Skip documentation deploy."
          else
            git commit -m "Update GitHub Pages"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
          fi

  deploy:
    name: Publish Package to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fmu-pem
    permissions:
      id-token: write # required for trusted publishing to PyPI

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: fmu-pem-dist
          path: dist/

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
