name: on-push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release-please:
    needs: test
    permissions:
      issues: write
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yaml

  update-documentation:
    name: Update Documentation
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 # for JSON schema generation
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Python Dependencies
        run: pip install .

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./documentation/package-lock.json

      - name: Install Node Dependencies
        working-directory: ./documentation
        run: npm ci

      - name: Create JSON Schema
        working-directory: ./documentation
        run: npm run create-json-schema

      - name: Build Documentation
        working-directory: ./documentation
        run: npm run docs:build

      - name: Deploy Documentation to GitHub Pages
        run: echo "Don't actually attempt this from my fork"
