name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: "If true, a release PR was merged"
        value: ${{ jobs.release-please.outputs.release_created }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
      - name: Outputs
        run: |
          echo "PR created/updated: ${{ steps.release.outputs.prs_created }}"
          echo "release created:    ${{ steps.release.outputs.release_created }}"
          echo "release tag:        ${{ steps.release.outputs.tag_name }}"
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
